### ISSUE TITLE
[AutoML Tables]  The provided location ID doesn't match  (js)

### ISSUE THREAD

**Issue by XinyueZ** [googleapis/nodejs-automl#411]
I get this error when I query my AutoML Tables model when I deploy a Firebase cloud function.

`Field: name; Message: The provided location ID doesn't match the endpoint. For automl.googleapis.com, the valid location ID is `us-central1`. For eu-automl.googleapis.com, the valid location ID is `eu`.`

additional stacktrace:
```
    at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/srv/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 3,
  metadata: 
   Metadata {
     _internal_repr: 
      { 'google.rpc.badrequest-bin': [Array],
        'grpc-status-details-bin': [Array],
        'grpc-server-stats-bin': [Array] },
     flags: 0 },
  details: 'List of found errors:\t1.Field: name; Message: The provided location ID doesn\'t match the endpoint. For automl.googleapis.com, the valid location ID is `us-central1`. For eu-automl.googleapis.com, the valid location ID is `eu`.\t',
  note: 'Exception occurred in retry method that was not classified as transient' } 
```

I believe I have set the location in `eu` correctly.

My model was deployed in `eu`, so I have to use `eu-automl.googleapis.com`.

My code:

```javascript
const project = 'some model project;
const region = 'eu';
const model = 'TBL45345345345345345';

const automl = require('@google-cloud/automl').v1beta1;
const clientOptions = { apiEndpoint: 'eu-automl.googleapis.com' };
const modelClient = new automl.AutoMlClient(clientOptions);
const predictionClient = new automl.PredictionServiceClient(clientOptions);

const projectLocation = modelClient.locationPath(project, region);

```
Both won't find location ID successfully:

```javascript
const requestModel = {
        name: modelClient.modelPath(project, region, model),
};
modelClient.getModel(requestModel) .......
const requestPrediction = {
        name: predictionClient.modelPath(project, region, model),
        payload: payload,
        params: { feature_importance: true },
 };
 predictionClient.predict(requestPrediction).......
```

**Comment by munkhuushmgl** [comment]
Just started on this, will provide the feedback soon.

**Comment by munkhuushmgl** [comment]
Looks like you may have been mixing up modelClient and predictionClient together which might have resulted this error.
Otherwise, it is working as intended on my end:

code snippet used:
```
const project = 'java-******';
const region = 'eu';
const model = 'TBL00000000000000';

const automl = require('@google-cloud/automl').v1beta1;
const clientOptions = {apiEndpoint: 'eu-automl.googleapis.com'};
const predictionClient = new automl.PredictionServiceClient(clientOptions);

const payload = {
  row: {
    values: [{stringValue: 'hello, world'}],
  },
};

predictionClient
  .predict({
    name: predictionClient.modelPath(project, region, model),
    payload: payload,
    params: {feature_importance: true},
  })
  .then(responses => {
    console.log(responses);
    console.log('Prediction results:');

    for (const result of responses[0].payload) {
      console.log(`Predicted class name: ${result.displayName}`);
      console.log(`Predicted class score: ${result.tables.score}`);

      // Get features of top importance
      const featureList = result.tables.tablesModelColumnInfo.map(
        columnInfo => {
          return {
            importance: columnInfo.featureImportance,
            displayName: columnInfo.columnDisplayName,
          };
        }
      );
      // Sort features by their importance, highest importance first
      featureList.sort((a, b) => {
        return b.importance - a.importance;
      });

      // Print top 10 important features
      console.log('Features of top importance');
      console.log(featureList.slice(0, 10));
    }
  })
  .catch(err => {
    console.error(err);
  });

```

model (region EU)

**Comment by munkhuushmgl** [comment]
Feel free to reopen if you still experiencing same error
