### ISSUE TITLE
Field: payload.payload; Message: Required field not set (only when deployed)

### ISSUE THREAD

**Issue by 404-html** [googleapis/nodejs-automl#436]
#### Environment details

  - Node.js version: 10
   - `@google-cloud/automl` version: 2.2.0

Stack tracke:
```
Error: 3 INVALID_ARGUMENT: List of found errors:	1.Field: payload.payload; Message: Required field not set.	
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.handleTrailers (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:262:14)
    at ClientHttp2Stream.emit (events.js:198:13)
    at emit (internal/http2/core.js:265:8)
```

Works fine if I call `predict` method from my local environment.
Errors after deploying to GC AppEngine.
Nothing changed in my code.
I double checked and I'm sure that payload is passed in arguments.
It works fine on version I deployed on Jul 21, 2020.
I trained new model and I'm getting the same issue.

Here's my code:

```js
const automl = require('@google-cloud/automl');
// Create client for prediction service.

const client = new automl.PredictionServiceClient();
const projectId = 'XXX';
const computeRegion = 'us-central1';
const modelId = 'XXX';

// Get the full path of the model.
const modelFullId = client.modelPath(projectId, computeRegion, modelId);

const payload = {
	"row": {
		"values": [
			{
				"numberValue": 6
			},
			{
				"numberValue": 0
			},
			{
				"numberValue": 0
			},
			{
				"numberValue": 0
			},
			{
				"stringValue": "Turkey"
			},
			{
				"stringValue": "Vinyl"
			},
			{
				"stringValue": "7inch"
			},
			{
				"stringValue": "45 RPM"
			},
			{
				"stringValue": "Mini-Album"
			},
			{
				"numberValue": 3
			},
			{
				"numberValue": 0
			},
			{
				"numberValue": 47.62
			}
		]
	}
}

const data = await client.predict({
			name: modelFullId,
			payload: payload,
			params: {}
		});
```

**Comment by 404-html** [comment]
I don't have this problem when using `@google-cloud/automl` version `1.2.4`.
The model was trained mode than one year ago so maybe that's the cause? 
From the other side I had the same issue with new model and recent `@google-cloud/automl` version.

**Comment by munkhuushmgl** [comment]
I was not able to reproduce this issue.

**Comment by munkhuushmgl** [comment]
@404-html Is this Tables or NL?

**Comment by 404-html** [comment]
Hey @munkhuushmgl, it's Tables.

**Comment by munkhuushmgl** [comment]
@404-html I think you are missing beta version on instantiating the client
```
const client = new automl.v1beta1.PredictionServiceClient();
```

you could use this as reference
https://github.com/googleapis/nodejs-automl/blob/master/samples/tables/predict.v1beta1.js
